pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('flask-app') {
                    sh 'docker build -t flask-devsecops-app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                dir('flask-app') {
                    sh '''
                        docker stop flask-devsecops-app || true
                        docker rm flask-devsecops-app || true
                        fuser -k 5000/tcp || true
                        docker run -d -p 5000:5000 --name flask-devsecops-app flask-devsecops-app
                    '''
                }
            }
        }

        stage('Test Application') {
            steps {
                script {
                    def response = sh(script: "curl -s -o /dev/null -w '%{http_code}' http://localhost:5000", returnStdout: true).trim()
                    if (response != '200') {
                        error("Health check failed! Expected HTTP 200, but got ${response}")
                    } else {
                        echo "Health check passed! App is running successfully."
                    }
                }
            }
        }
    }
}
