pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                dir('flask-app') {
                    sh 'docker build -t flask-devsecops-app .'
                }
            }
        }

        stage('Run Container') {
            steps {
                dir('flask-app') {
                    sh '''
                        # Stop existing container if running
                        docker stop flask-devsecops-app || true
                        docker rm flask-devsecops-app || true

                        # Kill any process using port 5000
                        fuser -k 5000/tcp || true

                        # Run new container
                        docker run -d -p 5000:5000 --name flask-devsecops-app flask-devsecops-app
                    '''
                }
            }
        }
    }
}
